### ISSUE TITLE
[Request] Upgrade to PHP7

### ISSUE THREAD

**Issue by rix1337** [linuxserver/docker-baseimage-alpine-nginx#10]
PHP5 is in its final lifespan, the latest 5.6 has just moved in the "security fixes only" phase. More Info [here](http://php.net/supported-versions.php).

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

In its current form the container is working fine, and PHP5.6 should remain somewhat secure for the next 2 years. I suggest moving to 7.0 or even better 7.1, due to its performance gains (may be negligible to most users of your containers). Mainly though, this baseimage is used in your awesome letsencrypt container, which should be secure, light-weight and **up-to-date**.

I know, alpine packages for PHP7< are rare/in their early phases, but would appreciate an update sometime in the future.

Cheers

**Comment by aptalca** [comment]
Planned for the big update including alpine 3.5 and nginx 1.10.2

**Comment by rix1337** [comment]
This is awesome news :)
