### ISSUE TITLE
features SQL

### ISSUE THREAD

**Issue by sardinhagym** [linuxserver/docker-baseimage-alpine-nginx#104]
hello Guys, I've been using this wonderful container " image: lscr.io/linuxserver/nginx:latest" but I needed it to have a sql:server driver and odbc sql server. I used the article below to try to install directly in the container but without success.
"https://learn.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16"
  could you add this feature?
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by j0nnymoe** [comment]
We won't add this to the container as 99% of the users won't need it, but you can use methods listed here to install it on boot https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
