### ISSUE TITLE
[BUG] Recent change overwrites php-local.ini with default timezone and wipes custom settings

### ISSUE THREAD

**Issue by Rollese** [linuxserver/docker-baseimage-alpine-nginx#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/config/php/php-local.ini gets overwritten with docker default timezone on startup and all custom settings are wiped

This is super dangerous as it wipes important custom settings including security changes like disable_functions configuration!

The breaking change was made in this commit:
https://github.com/linuxserver/docker-baseimage-alpine-nginx/commit/faeeefef00b54d2c81e48e3349e1540f39c5a171#diff-54ef142e71bec14efcd53bdbcf19908159e334653c81cab8541c520ba06125b7R15
root/etc/s6-overlay/s6-rc.d/init-php/run
```
# set default timezone
printf "date.timezone = %s\\n" "${TZ:-UTC}" >/config/php/php-local.ini
```

### Expected Behavior

The php-local.ini file should not be overwritten and keep all of its custom settings

### Steps To Reproduce

Modify php-local.ini and restart the container. The settings will be wiped with only one line containing "date.timezone" setting and the custom settings will not take effect

### Environment

```markdown
- OS: Unraid 6.12.13
- How docker service was installed: Unraid docker system
```

### Docker creation

```bash
Unraid docker creation with default settings
```

### Container logs

```bash
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 1.26.2-r3-ls302
Build-date: 2024-12-20T10:13:15+00:00
───────────────────────────────────────
    
using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│            │ 2024-07-16 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by thespad** [comment]
Thanks for reporting this, the timezone config should have been part of the first-run if block and not applying on every startup. I'll get the above PR merged and push rebuilds of any downstream images using this version of the base.
