### ISSUE TITLE
resty.http and cjson packages

### ISSUE THREAD

**Issue by demonspork** [linuxserver/docker-baseimage-alpine-nginx#30]
I am implementing some features in my environment (namely, https://github.com/cloudflare/nginx-google-oauth ) and they require some lua packages that aren't present in your letsencrypt or nginx containers.

lua5.1-resty-http
lua5.1-cjson

In an effort to avoid having to fork and build my own docker containers, if it isn't too much trouble, can you add these packages to your containers? If not, I understand and I will start reading the tutorials.

**Comment by aptalca** [comment]
Sure, we can add those. But not to the baseimage. They'll be added to the letsencrypt and nginx images.
