### ISSUE TITLE
Update Alpine to 3.13.3 to fix openssl vulnerability

### ISSUE THREAD

**Issue by daverof** [linuxserver/docker-baseimage-alpine-nginx#76]
Hi,
Can this please be updated to 3.13.3 as the openssl vulnerability will be affecting all SWAG users?

https://arstechnica.com/gadgets/2021/03/openssl-fixes-high-severity-flaw-that-allows-hackers-to-crash-servers/
https://alpinelinux.org/posts/Alpine-3.13.3-released.html

**Comment by aptalca** [comment]
Done. Thanks for the heads up. Swag is also pushing an update as we speak.
